// <auto-generated />
using CSharpFinal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CSharpFinal.Migrations
{
    [DbContext(typeof(CSharpFinalContext))]
    [Migration("20180815195552_TrueMigration")]
    partial class TrueMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("CSharpFinal.Models.Bidder", b =>
                {
                    b.Property<int>("BidderId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProductId");

                    b.Property<int>("UserId");

                    b.Property<double>("user_bid");

                    b.HasKey("BidderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Bidders");
                });

            modelBuilder.Entity("CSharpFinal.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CurrentBid");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("ProductDesc");

                    b.Property<string>("ProductName");

                    b.Property<int>("SellerId");

                    b.HasKey("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CSharpFinal.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.Property<double>("Wallet");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CSharpFinal.Models.Bidder", b =>
                {
                    b.HasOne("CSharpFinal.Models.Product", "Product")
                        .WithMany("Bidders_On")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CSharpFinal.Models.User", "User")
                        .WithMany("Bidder_On")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CSharpFinal.Models.Product", b =>
                {
                    b.HasOne("CSharpFinal.Models.User", "Seller")
                        .WithMany("Selling")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
